### ISSUE TITLE
Hard coded files (mostly missing)

### ISSUE THREAD

**Issue by WolfgangFahl** [rc-dukes/dukes#10]
```
pan:dukes wf$grep Users/jpoint/Repositories $(find . -name *.java)
./boss-hogg/src/main/java/nl/vaneijndhoven/dukes/bosshogg/BossHogg.java://        vertx.eventBus().sendObservable(Characters.DAISY.getCallsign() + "lane.start", new JsonObject().put("source", "file://Users/jpoint/Repositories/opencv-playground/src/main/resources/videos/full_run.mp4"));
./daisy/src/main/java/nl/vaneijndhoven/opencv/video/StartLightDetectionController.java:            this.capture.open("file://Users/jpoint/Repositories/opencv-playground/src/main/resources/videos/startlamp2.m4v");
./daisy/src/main/java/nl/vaneijndhoven/opencv/video/LaneDetectionGUI.java://             this.capture.open("file://Users/jpoint/Repositories/opencv-playground/src/main/resources/videos/stopzone2.m4v");
./daisy/src/main/java/nl/vaneijndhoven/opencv/video/LaneDetectionGUI.java:             this.capture.open("file://Users/jpoint/Repositories/opencv-playground/src/main/resources/videos/full_run.mp4");
./duke-farm/src/main/java/nl/vaneijndhoven/dukes/dukefarm/DukeFarm.java://                vertx.eventBus().send(Events.STREAMADDED.name(), new JsonObject().put("source", "file://Users/jpoint/Repositories/dukes/daisy/src/main/resources/videos/full_run.mp4"));
./cooter/src/test/java/nl/vaneijndhoven/dukes/cooter/CameraMatrixTest.java:        Files.newDirectoryStream(Paths.get("/Users/jpoint/Repositories/dukes/cooter/target/test-classes/cameramatrix"),
./cooter/src/test/java/nl/vaneijndhoven/dukes/cooter/CameraMatrixTest.java:        Mat image = Imgcodecs.imread("/Users/jpoint/Repositories/dukes/cooter/target/test-classes/cameramatrix/test_image.jpg");
./cooter/src/test/java/nl/vaneijndhoven/dukes/cooter/CameraMatrixTest.java:        Imgcodecs.imwrite("/Users/jpoint/Repositories/dukes/cooter/target/test-classes/cameramatrix/debug.jpg", undistorted);
./cooter/src/test/java/nl/vaneijndhoven/dukes/cooter/PerspectiveShiftTest.java://        Files.newDirectoryStream(Paths.get("/Users/jpoint/Repositories/dukes/cooter/target/test-classes/perspectiveshift"),
./cooter/src/test/java/nl/vaneijndhoven/dukes/cooter/PerspectiveShiftTest.java:        Mat original = Imgcodecs.imread("/Users/jpoint/Repositories/dukes/cooter/target/test-classes/perspectiveshift/screen_shot.png");
./cooter/src/test/java/nl/vaneijndhoven/dukes/cooter/PerspectiveShiftTest.java:        Imgcodecs.imwrite("/Users/jpoint/Repositories/dukes/cooter/target/test-classes/perspectiveshift/debug.jpg", image);
./cooter/src/test/java/nl/vaneijndhoven/dukes/cooter/PerspectiveShiftTest.java:        Imgcodecs.imwrite("/Users/jpoint/Repositories/dukes/cooter/target/test-classes/perspectiveshift/debug2.jpg", shifted);
./uncle-jesse/src/main/java/nl/vaneijndhoven/dukes/unclejesse/StartLightDetectionController.java://            this.capture.open("file://Users/jpoint/Repositories/opencv-playground/src/main/resources/videos/startlamp2.m4v");
./uncle-jesse/src/main/java/nl/vaneijndhoven/dukes/unclejesse/LaneDetectionGUI.java:////             this.capture.open("file://Users/jpoint/Repositories/opencv-playground/src/main/resources/videos/stopzone2.m4v");
./uncle-jesse/src/main/java/nl/vaneijndhoven/dukes/unclejesse/LaneDetectionGUI.java://             this.capture.open("file://Users/jpoint/Repositories/opencv-playground/src/main/resources/videos/full_run.mp4");
```

**Comment by bertjan** [comment]
@timve do you still have these files used in the tests? If you, can you add them (or put them on WeTransfer or something so @WolfgangFahl can add them and test)

**Comment by timve** [comment]
`file://Users/jpoint/Repositories/opencv-playground/src/main/resources/videos/full_run.mp4`
`file://Users/jpoint/Repositories/opencv-playground/src/main/resources/videos/startlamp2.m4v`
`file://Users/jpoint/Repositories/opencv-playground/src/main/resources/videos/stopzone2.m4v`

These are large files, probably not wise to add to the source tree? I have uploaded them to WeTransfer https://we.tl/t-SfjUujW45G

`./cooter/src/test/java/nl/vaneijndhoven/dukes/cooter/CameraMatrixTest.java:        Files.newDirectoryStream(Paths.get("/Users/jpoint/Repositories/dukes/cooter/target/test-classes/cameramatrix"),`

This uses files from test resources which are present in source control, should be present in the target/test-classes dir after compilation of test sources (path will be different of course)

`./cooter/src/test/java/nl/vaneijndhoven/dukes/cooter/CameraMatrixTest.java:        Mat image = Imgcodecs.imread("/Users/jpoint/Repositories/dukes/cooter/target/test-classes/cameramatrix/test_image.jpg");`

Same as the previous comment.

`./cooter/src/test/java/nl/vaneijndhoven/dukes/cooter/CameraMatrixTest.java:        Imgcodecs.imwrite("/Users/jpoint/Repositories/dukes/cooter/target/test-classes/cameramatrix/debug.jpg", undistorted);`

This is debug output (it is generated when the test runs).

`./cooter/src/test/java/nl/vaneijndhoven/dukes/cooter/PerspectiveShiftTest.java://        Files.newDirectoryStream(Paths.get("/Users/jpoint/Repositories/dukes/cooter/target/test-classes/perspectiveshift")`

This uses files from test resources which are present in source control, should be present in the target/test-classes dir after compilation of test sources (path will be different of course)

`./cooter/src/test/java/nl/vaneijndhoven/dukes/cooter/PerspectiveShiftTest.java:        Mat original = Imgcodecs.imread("/Users/jpoint/Repositories/dukes/cooter/target/test-classes/perspectiveshift/screen_shot.png");`

Same as above

`./cooter/src/test/java/nl/vaneijndhoven/dukes/cooter/PerspectiveShiftTest.java:        Imgcodecs.imwrite("/Users/jpoint/Repositories/dukes/cooter/target/test-classes/perspectiveshift/debug.jpg", image);`

This is debug output (it is generated when the test runs).

`./cooter/src/test/java/nl/vaneijndhoven/dukes/cooter/PerspectiveShiftTest.java:        Imgcodecs.imwrite("/Users/jpoint/Repositories/dukes/cooter/target/test-classes/perspectiveshift/debug2.jpg", shifted);`

This is debug output (it is generated when the test runs).

**Comment by WolfgangFahl** [comment]
Some files can now be found on the BITPlan wiki:

* http://wiki.bitplan.com/videos/full_run.mp4
* http://wiki.bitplan.com/videos/startlamp2.m4v
* http://wiki.bitplan.com/videos/stopzone2.m4v
