### ISSUE TITLE
Improve Javadoc - first steps

### ISSUE THREAD

**Issue by WolfgangFahl** [rc-dukes/dukes#11]
make JavaDoc available e.g. via github pages and potentially use UmlDoclet to generate plantuml diagrams https://github.com/talsma-ict/umldoclet/blob/develop-v1/docs/USAGE.md

**Comment by WolfgangFahl** [comment]
There is now a gh-pages branch in dukes to publish javadoc and similare
reports with mvn site.

To enable

https://rc-dukes.github.io/dukes

the following the instructions in:

https://help.github.com/en/articles/configuring-a-publishing-source-for-github-pages
need to be followed

It will take about 10 minutes for the gh-pages page to activate after
you have configured it.

**Comment by bertjan** [comment]
Should be set up now - can you check?

**Comment by WolfgangFahl** [comment]
I renamed this to "first steps" and will close it. For further improvements i might open another issue.
