### ISSUE TITLE
Refactor module naming to conceptual integrity

### ISSUE THREAD

**Issue by WolfgangFahl** [rc-dukes/dukes#13]
The https://en.wikipedia.org/wiki/The_Dukes_of_Hazzard names used should be refactored and only be used as nicknames for modules. The real module name should reflect the concepts.

e.g.
roi=cletus
detect=daisy
geometry=enos
watchdog=flash
common=hazard county

...

**Comment by bertjan** [comment]
Agreed - the character names made it relatively hard to find the right module ;-)

**Comment by bertjan** [comment]
whoops, accidentally closed this issue

**Comment by timve** [comment]
Hehe, yes in our talks I always emphasise this not being proper architecture in any way

**Comment by WolfgangFahl** [comment]
![grafik](https://user-images.githubusercontent.com/1336221/60098529-021dcd80-9756-11e9-9b07-d0a84200671a.png)

**Comment by WolfgangFahl** [comment]
![grafik](https://user-images.githubusercontent.com/1336221/60098645-51fc9480-9756-11e9-9bf5-0fe8843e9c1b.png)
