### ISSUE TITLE
Remove superfluous opencv libraries spread over the project

### ISSUE THREAD

**Issue by WolfgangFahl** [rc-dukes/dukes#15]
```
find . -name *opencv_java* | grep -v target
./daisy/src/main/resources/lib/osx/libopencv_java310.dylib
./daisy/src/main/resources/lib/osx-bj/libopencv_java330.dylib
./daisy/src/main/resources/lib/osx2/libopencv_java310.so
./daisy/src/main/resources/lib/osx2/libopencv_java310.dylib
./roscoe/src/main/resources/lib/osx/libopencv_java310.dylib
./roscoe/src/main/resources/lib/osx-bj/libopencv_java330.dylib
./roscoe/src/main/resources/lib/osx2/libopencv_java310.so
./roscoe/src/main/resources/lib/osx2/libopencv_java310.dylib
./rc-camera-matrix/src/main/resources/lib/osx/libopencv_java310.dylib
./rc-camera-matrix/src/main/resources/lib/osx-bj/libopencv_java330.dylib
./rc-camera-matrix/src/main/resources/lib/osx2/libopencv_java310.so
./rc-camera-matrix/src/main/resources/lib/osx2/libopencv_java310.dylib
./rc-camera-matrix/src/main/resources/lib/osx-tim/libopencv_java330.dylib
./lib/libopencv_java343.dylib
./rc-roi/src/main/resources/lib/osx-bj/libopencv_java330.dylib
./rc-roi/src/main/resources/lib/osx-tim/libopencv_java330.dylib
```

**Comment by bertjan** [comment]
Agreed. Maybe we could create one centralized dependency that has the OpenCV libs, and depend on that lib from the other modules?
Or add an external lib in the parent pom and have all submodules use that.

**Comment by timve** [comment]
This could probably be solved by using dependencyManagement in the parent pom and then add the dependency by only using artifact and group?
I would advice against adding the dependency in the parent submodule which will cause all submodules to have the dependency even though they do not have any opencv dependencies.

**Comment by WolfgangFahl** [comment]
Thanks for the discussion. The approach from how to fake a maven dependency to be resolved locally https://stackoverflow.com/a/31023523/1497139 has been in place for a few commits already now and it seems to work pretty well (at least in the Mac OS environment). Together with https://stackoverflow.com/a/56740465/1497139 the Native Library handling is at least getting simpler and more convenient. To make a Windows or Linux server possible will be another issue.
