### ISSUE TITLE
TestAction fails

### ISSUE THREAD

**Issue by WolfgangFahl** [rc-dukes/dukes#25]
see https://github.com/rc-dukes/dukes/blob/master/rc-action/src/test/java/nl/vaneijndhoven/dukes/action/TestAction.java

I've ignored the Junit Test for the time being. 
Tim could you please look into this and comment?

**Comment by timve** [comment]
There was a timing issue: the `StraightLaneNavigator` only emits navigation commands if the previous command was longer ago than a set interval. The initial value for last sent is set at initialisation, if the call to navigate arrives to soon, the result will be ignored.

I have also altered the code to use `TestSubscriber` (specialised class for testing Observables provided by RxJava)

**Comment by WolfgangFahl** [comment]
Thx - that is helpful for understanding how the navigation works
