### ISSUE TITLE
Allow download of recorded media

### ISSUE THREAD

**Issue by WolfgangFahl** [rc-dukes/dukes#50]
recorded photos and videos shoot be made available for download

**Comment by WolfgangFahl** [comment]
see https://github.com/vert-x3/vertx-web/issues/204 for the problems with this

**Comment by pmlopes** [comment]
Full disk access is disabled by default. This was a design decision to secure user servers, a badly configured server running with a privileged user (root for example) could just allow the full `/etc` directory to be dumped or even non application related data.

After careful analysis is up to the developer to allow it or not with:

```java
StaticHandler.create()
  .setAllowRootFileSystemAccess(true)
  .setWebroot('/home/myuser')
```

**Comment by WolfgangFahl** [comment]
@pmlopes - thx works like a charm ...
