### ISSUE TITLE
make GPIO pins configurable and document 

### ISSUE THREAD

**Issue by WolfgangFahl** [rc-dukes/dukes#8]
The original wiring is:

- MOTOR: GPIO-17 - Servoblaster ID 1
- WHEEL: GPIO-18 - Servoblaster ID 2
- LED: GPIO-24 - Servolbaster ID 6

The wiring should be documented and configurable in case another wiring is applied.

**Comment by bertjan** [comment]
Good plan. It would be nice to have a GPIO pin layout in the README so it's easy to see which GPIO pins are used for what.

**Comment by WolfgangFahl** [comment]
The first step is done - I'll keep this issue open until there is support for another servo device which works differently then Servoblaster.

**Comment by WolfgangFahl** [comment]
The device independence is meanwhile addressed in #38
